<?php

namespace MainBundle\Entity;

/**
 * AvionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAvionsDispo(){
        $qb = $this->_em->createQuery("SELECT a FROM MainBundle:Avion a WHERE NOT EXISTS (SELECT v FROM MainBundle:Vol v where v.avion = a.id)");
        $pilotes = $qb->getResult();
        return $pilotes;
    }
}
