<?php

namespace MainBundle\Entity;

/**
 * VolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VolRepository extends \Doctrine\ORM\EntityRepository
{
    public function findVolByPassager($passager){
        $qb = $this->createQueryBuilder("v")
            ->where(':passager MEMBER OF v.passagers')
            ->setParameters(array('passager' => $passager))
        ;
        return $qb->getQuery()->getResult();

    }
    public function findVolByPilote($passager){
        $qb = $this->createQueryBuilder("v")
            ->where(':passager MEMBER OF v.passagers')
            ->setParameters(array('passager' => $passager))
        ;
        return $qb->getQuery()->getResult();

    }

}
